apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-python
  labels:
    app: sample-app-python
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-app-python
  template:
    metadata:
      labels:
        app: sample-app-python
    spec:
      containers:
      - name: sample-app-python
        image: vishnudeeli0/python-k8s
        ports:
        - containerPort: 8000
